### ISSUE TITLE
[JSS][Phulwari] Implement Attendance for Phulwari.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#29]
https://docs.google.com/spreadsheets/d/14fvLwLFfPd50uPhashTGta5rf9S1ItG2H3LOt9vK_tc/edit?ts=60374b68#gid=578912605

**Tasks -** 
- [x] Phulwari Registration form
- [x] Daily attendance form
- [x] Attendance cancel form
- [x] Absent followup form (for child in Phulwari Program)
- [x] Visit scheduling for Attendance form and Absent followup form.

**Comment by garimadosar5** [comment]
QA Notes - 
- Skip is not working in Phulwari program
- Visit scheduling not working for children enrolled in phulwari.

**Comment by garimadosar5** [comment]
**Changes discussed -** 
- [ ] What can be the reason of child to be absent in Phulwari? Add two more options.
    1.  Exit
    2. Death
- [ ] Add new question - "Date of phulwari resume"
- [ ] Do not schedule any child followup till date of phulwari resume. If child is present before the phulwari resume date then again start scheduling followup if child is absent.
- [ ] On Phulwari group, add validation.
- [ ]

**Comment by nupoorkhandelwal** [comment]
set role jssuat;
insert into group_subject(uuid, group_subject_id, member_subject_id, group_role_id, membership_start_date, membership_end_date, organisation_id, audit_id, version)
select uuid_generate_v4(),
       (select id from individual where first_name = enl.observations -> '6129d59e-17ee-4e0d-a48d-df00b0df326b' ),
       individual_id,
       123,
       current_timestamp,
       null,
       128,
       create_audit((select id from users where username = 'nupoor@jssuat')),
       0
from program_enrolment enl;

**Comment by garimadosar5** [comment]
**QA Notes -** 
Case - Jahnvi Su, this child is enrolled in "Dongritola" Phulwari but it got associated with Phulwari "Payari Phulwari Attendance". Please check.
