### ISSUE TITLE
[JSS Phulwari] ETL Migration

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss#84]
Earlier, JSS Phulwari reports on metabase were working fine but some how the performance has gone down and now the client is unable to access them.

So to unblock client, following set of reports need to picked up on priority -

- [ ] Grade change  [Track here](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jss/85)
- [ ] Grade change linelist  [Track here](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jss/85)
- [ ] Grade change linelist weight not taken [Track here](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jss/85)
- [ ] Phulwariwise list of children absent for more than 3 days
- [ ] Phulwariwise Monthly Attendance Report
- [ ] Population Standard
- [ ] Weight For Age Grade-Phulwari Children
- [x] Due Visits

Following reports can be worked upon later -

- [ ] All children with first and last measurements for specific dates
- [ ] Average Numbers for Phulwari
- [ ] Faltering Children
- [ ] Children Moved to Lower WFA grade
- [ ] Children Moved to Upper WFA grade
- [ ] Line list of Children- weight not taken
- [ ] Monthly data of weight and Height
- [ ] New children enrolled in Phulwari in a month
- [ ] Number of registration VS enrolments
- [ ] Phulwari child weight gain (Enrolled Children)
- [ ] Test - Average weight gain over time
- [ ] User wise consolidated data

**Make sure all filters and drill down (wherever appliocable ) are working and nothing new breaks during this ETL migration**
