### ISSUE TITLE
[Support JSS] Fix a rule in Phulwari orgs

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss#89]
**Form** 
Daily Attendance Form

**Rule UUID** 
`9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3`

## Tasks -

- [ ] Fix the visit scheduling rule in all the Phulwari orgs (JSS, JSSCP, Singrauli) to avoid scheduling visit for a voided child subject
- [ ] Make change on all UAT and prod orgs
- [ ] Mark the rule failures corresponding to this error as closed = true

**Comment by BEULAHEVANJALIN** [comment]
There were two encounters types for the Phulwari subject type:

1. Daily Attendance Form
2. Observation Checklist


Daily Attendance Form schedules Daily Attendance Form & Child Absent Follow-up Form
The Observation Checklist does not schedule anything.

Seems these visit scheduling rules have already been updated, so there is nothing to fix. Also all these rule failures happened in 2021. So closing these rule failures now.

---
```sql
set role singrauli;

select *
from rule_failure_telemetry
where rule_uuid = '9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3'
  and is_closed is false
order by last_modified_date_time desc;

update rule_failure_telemetry
set is_closed        = true,
    closed_date_time = current_timestamp
where rule_uuid = '9f2af1f9-e150-4f8e-aad3-40bb7eb05aa3'
  and is_closed is false
  and organisation_id = 172;
```

Closed 7 open rule failures as part of this card.
